:feelpp: Feel++
= {feelpp} mqs 

image:https://github.com/feelpp/mqs/workflows/CI/badge.svg[CI]

This is a {feelpp} Template Project. It serves as a template for {feelpp} projects.

== Features

* script rename.sh to rename the project
* cmake environment
** cpack configuration
** ctest configuration
* antora environment
* github actions
* vscode integration using container

== Compile

=== Using Ninja

In the toplevel build directory, type

----
ninja
----

=== install data cases

In the toplevel build directory, type

----
ninja feelpp_add_testcase_cases
----

it will install the data in the build directory to ease the access to the application.
If you modify the cases files in the source directory, simply re-run the `ninja feelpp_add_testcase_cases` to update the data

== Get  simulation Data from remote location

----
mkdir $HOME/feel
rsync -avz <remote simulation server>:/home/<login>/feel/hifimagnet .
----

== First and second equation files 

The first equation name is test1, in the folder mqs/src.
.geo and .cfg files are stored in mqs/src/cases/test1/
To get the same simulation as implementation, type in build/src directory :

mpirun -np 1 feelpp_mqs_test1 --config-file cases/test1/test1.cfg 
You can also use the parameter --gmsh.hsize 0.01 and --pc-type gasm for exemple


The first equation name is test2, in the folder mqs/src.
.geo and .cfg files are stored in mqs/src/cases/test2/
To get the same simulation as implementation, type in build/src directory :

mpirun -np 1 feelpp_mqs_test2 --config-file cases/test2/test2.cfg 

for the first test, and 

mpirun -np 1 feelpp_mqs_test2 --config-file cases/test2/test22.cfg 

for the second test.

You can also use the parameter --gmsh.hsize 0.01 and --pc-type gasm for exemple

For the coupled equation, the name is mqs-blockform, in the folder mqs/src.
.geo and .cfg files are stored in mqs/src/cases/mqs-blockform/

To get a simulation (doesnt give good result for the moment), type in build/src directory :

mpirun -np 1 feelpp_mqs_mqs-blockform --config-file cases/mqs-blockform/const.cfg 