= Conclusion

We can see that the transition between the project and the internship went rather well. The outstanding goal at the end of the project was to have a viable simulation of the two examples with one and two magnets, and to have a functional code to simulate these cases. 
As we have seen, the results are quite close to the results obtained with getdp, although with a slight discrepancy.

The next two objectives of the course were the implementation of the BDF scheme and the coupling of the MQS equations with the heat equation. For the BDF part, we find well the results obtained with an implicit Euler scheme, which is satisfactory. 
For the MQS and heat coupling, 3 methods of resolution have been considered, and two have been programmed. 

With the first method, the resolution with linear parameter, we find on the one hand the results obtained previously on MQS, and we obtained for the temperature results very close to the theoretical result. 

For the second method, the resolution with non-linear parameters, we were able to compare in particular the paces of the intensity and the magnetic field with the previous case, to note that the results obtained satisfied several expected points, such as the peak linked to the linear non-linear transition, or the proportionality between I and B. This is therefore a good sign for the operation of the program.

In the future, it would be good to program the 3rd method, which is the resolution of the 3 equations at the same time, using a block structure for example.
Moreover, although using the feelpp tools, the code is not implemented as a feelpp class, and a rewriting in this form must be strongly considered, in order to allow future implementation in feelpp.