= Modeling the transient behavior of high field magnets

== Introduction

High field magnets are a tool in many research fields such as superconductivity or BioChemistry. Only a few laboratories, 
including the National Laboratory for Intense Magnetic Fields (LNCMI) in France, supply such magnets, which are made 
available to the scientific community via calls for projects. LNCMI is a research infrastructure run by the CNRS, located on 
two sites: Grenoble, where continuous fields up to 37 teslas can be reached during several hours, and Toulouse where pulsed fields 
up to 100 tesla are achieved within a few hundreds of milliseconds. Their development and maintenance represent a significant cost. 
This is why it is fundamental to understand and model these magnets beforehand. 


== Context

Such High Field Magnets are made of copper alloy since superconductor can only generate up to 25 tesla with the present technology.
To obtain an intense magnetic field, it is necessary to pass a sufficiently important current, 
of the order of 30000 Ampere, in coils. Therefore they have to be cooled down by a forced water flow to dissipate Heat generated by Joule losses.
The cooling is usually modelled by heat exchange coefficients, which are introduced as the boundary conditions for the thermal problem.  
Moreover, the magnets shall withstand the electromagnetic efforts. This calls for multi-physics modelling. 

Models for the transient regime have developed in the frame of a collaboration between the LNCMI and IRMA. The models heavily relie on the
feelpp toolboxes. In this study, we will target the starting and stopping the magnets. We will focus on the electromagnetic model - namely 
a formulation of Maxwell's equations, in the quasi-static case, i.e. the formulation in magnetic and electric potential.   

== End of the project, beginning and objective of the stage

At the end of the project, we had validated the tests on each of the equations individually, but we were not getting good results for the coupling. 
At the beginning of the stage, I took a code created by Christophe Trophime, aiming at implementing the two equations as a block, and solving the associated matrix system. The functionning will be explained in next section.

First, the objective of the stage is to complete and validate the resolution of the two MQS equations. Then, we look at another time scheme, the BDF scheme. Finally, the final objective is to add to our two equations the influence of temperature, through the heat equation, because some parameters actually depend on temperature. We will therefore see several methods of implementation of this equations

