= Add the heat equation 

== The heat equation

Let's consider a domain stem:[\Omega], and note stem:[\Gamma] the edge of the domain. 
Let's assume that stem:[\Gamma] is divided into 3 sub-domains, stem:[\Gamma_D], stem:[\Gamma_N], and stem:[\Gamma_R].
The heat equation is expressed as follows :

[stem]
++++
\begin{align}
\rho Cp\frac{\partial T}{\partial t} - \nabla \cdot ( k \nabla T) = f \qquad \text{on $\Omega \times \mathbb{R}^+$} \\
T(x,t=0) = T_0 \\
T(x,t) = g(x,t) \qquad \text{on $\Gamma_D \times \mathbb{R}^+$} \\
-k \frac{\partial T}{\partial n} = m(x,t) \qquad \text{on $\Gamma_N \times \mathbb{R}^+$} \\
-k\frac{\partial T}{\partial n} = h(T-T_w) \qquad \text{on $\Gamma_R \times \mathbb{R}^+$} \\
\end{align}
++++

Where :

* stem:[T] is the temperature 
* stem:[T_0] is the initial temperature 
* stem:[f] is the source temperature 
* stem:[g] and stem:[m] are Dirichlet and Neumann conditions 
* stem:[Cp] is the specific heat capacity 
* stem:[\rho] is the density of the material  
* stem:[h] and stem:[T_w] are two parameters. 

== Weak formulation

Let's note stem:[V = \{v \in H^1(\Omega) | v = g \text{ on $\Gamma_D$}\}] 
and stem:[V_0 = \{v \in H^1(\Omega) | v = 0 \text{ on $\Gamma_D$}\}].

Let's take stem:[T \in V] and stem:[v \in V_0]. 
By multiplying our equation by v and integrating we have :

[stem]
++++
\begin{equation*}
\int_{\Omega} \rho C_p \frac{\partial T}{\partial t} \cdot v - \int_{\Omega} \nabla \cdot ( k \nabla T) \cdot v = \int_{\Omega} f \cdot v
\end{equation*}
++++

Using the relationship: 

[stem]
++++
\nabla \cdot (u \cdot v) = v \cdot \nabla u + u \nabla \cdot v
++++

and using the divergence theorem we get : 



[stem]
++++
\begin{equation*}
\int_{\Omega} \rho C_p \frac{\partial T}{\partial t} \cdot v + \int_{\Omega} k \nabla T \cdot \nabla v - \int_{\Gamma} k \frac{\partial T}{\partial n} \cdot v = \int_{\Omega} f \cdot v
\end{equation*}
++++

Or :

[stem]
++++
\begin{align}
v = 0 \qquad \text{on $\Gamma_D$ } \\
-k \frac{\partial T}{\partial n} = m(x,t) \qquad \text{on $\Gamma_N$} \\
-k\frac{\partial T}{\partial n} = h(T-T_w) \qquad \text{on $\Gamma_R$ } \\
\end{align}
++++

so finally we have :

[stem]
++++
\begin{equation*}
\int_{\Omega} \rho C_p \frac{\partial T}{\partial t} \cdot v + \int_{\Omega} k \nabla T \cdot \nabla v + \int_{\Gamma_R} h T \cdot v = \int_{\Omega} f \cdot v + \int_{\Gamma_R} h T_w \cdot v - \int_{\Gamma_N} m \cdot v
\end{equation*}
++++

== Implementation under feelpp

== MQS with heat equation

First, let's remember the two equations of the MQS model :

[stem]
++++
\begin{align*}
\nabla \times (\frac{1}{\mu}\,\nabla \times A) + \sigma  \frac{\partial A}{\partial t} = -\sigma \, \nabla V \\
\nabla \cdot (\sigma ( -\nabla V -\frac{\partial A}{\partial t})) = 0
\end{align*}
++++

where :

* stem:[A] is the magnetic potential 
* stem:[V] is the scalar electric potential
* stem:[\mu_0(r,t)] is the permeability of vaccum
* stem:[\sigma(r,t)] is the conductivity

We now wish to add the heat equation to the two equations of the mqs model. 
For this, the source term of the heat equation will be joule losses, defined by :

[stem]
++++
\begin{align*}
f 
& = J \cdot E \\
& = \sigma ||E||^2 \\
& = \sigma ||(\nabla V +\frac{\partial A}{\partial t})||^2 
\end{align*}
++++

so the heat part will be :

[stem]
++++
\begin{equation*}
\rho Cp\frac{\partial T}{\partial t} - \nabla \cdot (k \nabla T) = \sigma ||E||^2
\end{equation*}
++++

Finally we have the system :

[stem]
++++
\begin{align*}
\nabla \times (\frac{1}{\mu}\,\nabla \times A) + \sigma  \frac{\partial A}{\partial t} = -\sigma \, \nabla V \\
\nabla \cdot (\sigma ( -\nabla V -\frac{\partial A}{\partial t})) = 0 \\
\rho Cp\frac{\partial T}{\partial t} - \nabla \cdot (k \nabla T) = \sigma ||E||^2
\end{align*}
++++

Now, adding the weak formulation of the formulation section with the heat weak formulation, we have :

[stem]
++++
\begin{align*}
\int_{\Omega} \frac{1}{\mu} \, (\nabla \times \phi) \cdot (\nabla \times A) - \int_{\Gamma_D} \frac{1}{\mu} A_D \cdot (\nabla \times A) = - \int_{\Omega_C} \sigma \phi \cdot (\nabla V + \frac{\partial A}{\partial t}) \\
- \int_{\Omega_C} \sigma ( -\nabla V -\frac{\partial A}{\partial t}) \cdot \nabla \psi = 0 \\
\int_{\Omega} \rho C_p \frac{\partial T}{\partial t} \cdot v + \int_{\Omega} k \nabla T \cdot \nabla v + \int_{\Gamma_R} h T \cdot v = \int_{\Omega_C} \sigma ||E||^2 \cdot v + \int_{\Gamma_R} h T_w \cdot v - \int_{\Gamma_N} m \cdot v
\end{align*}
++++


