= Formulation
:stem: latexmath
:eqnums:

== Differential form of Maxwell's equations

Maxwell's equations, are laws of physics, constituting the basic postulates of electromagnetism. They translate, in local form, several theorems that governed electromagnetism, that Maxwell gathered in integral form.
These equations define relations between the electromagnetic fields and the source elements.
The differential form of Maxwell's equations is as follows:

[stem]
++++
\begin{align*}
\nabla \times H(r,t) &=& J(r,t) + \frac{\partial D(r,t)}{\partial t} \\
\nabla \times E(r,t) &=& -\frac{\partial B(r,t)}{\partial t} \\
\nabla \cdot B(r,t) &=& 0 \\
\nabla \cdot D(r,t) &=& \rho(r,t) \\
B(r,t) &=& \mu_0[H(r,t)+M(r,t)] \\
J(r,t) &=& \sigma[E(r,t)+E_i(r,t)] \\
D(r,t) &=& \epsilon_0 E(r,t) + P(r,t)
\end{align*}
++++

where : 

|===
|stem:[H(r,t)] | the magnetic field intensity,
|stem:[E(r,t)] | the electric field intensity,
|stem:[B(r,t)] | the magnetic flux density,
|stem:[D(r,t)] | the electric flux density,
|stem:[J(r,t)] | the electric current density,
|stem:[\rho(r,t)] | the electric charge density,
|stem:[M(r,t)] | the magnetization,
|stem:[E_i(r,t)] | the impressed electric field,
|stem:[P(r,t)] | the polarization,
|stem:[\mu_0(r,t)] | the permeability of vaccum,
|stem:[\sigma(r,t)] | the conductivity,
|stem:[\epsilon_0(r,t)] | the permittivity of vacuum.
|===

== The magnetic vector and electric scalar potentials formulation

We're interested in simplified equations:

[stem]
++++
\begin{align*}
\nabla \times H(r,t) &=& J(r,t) + \frac{\partial D(r,t)}{\partial t} \\
\nabla \times E(r,t) &=& -\frac{\partial B(r,t)}{\partial t} \\
\nabla \cdot B(r,t) &=& 0 \\
\nabla \cdot D(r,t) &=& 0 \\
B(r,t) &=& \mu_0H(r,t) \\
D(r,t) &=& \epsilon_0 E(r,t) \\
J(r,t) &=& \sigma E(r,t)
\end{align*}
++++

The MQS approximation consists in neglecting the so-called displacement current, aka stem:[\frac{\partial D}{\partial t}]. In this context, the equations to solve are:

[[Faraday]][[Ampere]]
[stem]
++++
\begin{align}
\nabla \times H(r,t) &=& J(r,t),\label{Ampere} \\
\nabla \times E(r,t) &=& -\frac{\partial B(r,t)}{\partial t}, \label{Faraday} \\
B(r,t) &=& \mu_0H(r,t) \\
J(r,t) &=& \sigma\,E(r,t)
\end{align}
++++

[NOTE]
The first two equations are respectively the so-called *Ampere* and *Faraday* equations.

A classical way to solve these equations is to introduce a magnetic potential stem:[A] and a scalar electric potential stem:[V]. As stem:[B] is a divergence free field, we can define stem:[A] as:
[stem]
++++
\begin{equation*}
B = \nabla \times A.
\end{equation*}
++++

To ensure stem:[A] unicity we will need to add a gauge condition. Most commonly:
[stem]
++++
\begin{equation*}
\nabla \cdot A = 0
\end{equation*}
++++

The <<Faraday, Faraday equation>> may, then, be rewritten as:
[stem]
++++
\begin{equation*}
\nabla \times (E +\frac{\partial A}{\partial t} ) = 0.
\end{equation*}
++++

We can define the electric scalar potential stem:[V] as:
[stem]
++++
\begin{equation*}
E +\frac{\partial A}{\partial t} = -\nabla V.
\end{equation*}
++++

It follows that:
[stem]
++++
\begin{equation*}
J = \sigma ( -\nabla V -\frac{\partial A}{\partial t}).
\end{equation*}
++++

From this expression of the current density, we may rewrite the <<Ampere, Ampere equation>> as:
[[nAmpere]]
[stem]
++++
\begin{equation}
\nabla \times (\frac{1}{\mu}\,\nabla \times A) + \sigma  \frac{\partial A}{\partial t} = -\sigma \, \nabla V.\quad\text{(1)}\label{nAmpere}
\end{equation}
++++

because :
[stem]
++++
\begin{equation*}
B = \nabla \times A = \mu H
\end{equation*}
++++
so : 
[stem]
++++
\begin{equation*}
\nabla \times H = \nabla \times ( \frac{1}{\mu} \nabla \times A)
\end{equation*}
++++

To this equation, we add the conservation of the current density:
[[nConservation]]
[stem]
++++
\begin{equation}
\nabla \cdot (J) = \nabla \cdot (\sigma ( -\nabla V -\frac{\partial A}{\partial t})) = 0\quad\text{(2)}
\end{equation}\label{nConservation}
++++

Equations <<nAmpere, (1)>> and <<nConservation, (2)>> are the equations that we will solve for the MQS model.

== Weak formulation

Let us note stem:[\Omega] the domain, comprising the conductor and the air, and let us note  stem:[\Gamma] the edge of this domain, namely the edge of the air, the inlet and the outlet.

Let's look at the set:
[stem]
++++
\begin{equation}
H_{curl}(\Omega) = \{v \in L^2(\Omega)| \nabla \times v \in L^2(\Omega)\}
\end{equation}
++++

We now consider the equation <<nAmpere, (1)>> : By multiplying by stem:[\phi \in H_{rot}(\Omega)] and by integrating on stem:[\Omega] we get : 

[stem]
++++
\begin{equation}
\int_{\Omega} \phi(\nabla \times (\frac{1}{\mu}\,\nabla \times A) + \sigma  \frac{\partial A}{\partial t}) = \int_{\Omega} \phi(-\sigma \, \nabla V)
\end{equation}
++++

Who can rewrite themselves:  

[stem]
++++
\begin{equation}
\int_{\Omega} \frac{1}{\mu} \, \phi\nabla \times (\nabla \times A) = - \int_{\Omega} \phi(\sigma \, \nabla V + \frac{\partial A}{\partial t})
\end{equation}
++++

Using the relationship: 
[stem]
++++
\nabla \cdot (u \times v) = v (\nabla \times u) - u (\nabla \times v)
++++

we deduce that:  
[stem]
++++
\begin{equation}
\int_{\Omega} \frac{1}{\mu} \, (\nabla \times \phi) \cdot (\nabla \times A) + \int_{\Omega} \frac{1}{\mu} \nabla \cdot (\phi \nabla \times A) = - \int_{\Omega} \phi(\sigma \, \nabla V + \frac{\partial A}{\partial t})
\end{equation}
++++

Using the divergence theorem we get: 

[stem]
++++
\begin{equation}
\int_{\Omega} \frac{1}{\mu} \, (\nabla \times \phi) \cdot (\nabla \times A) + \int_{\Gamma} \frac{1}{\mu} \phi \cdot (\nabla \times A)\cdot n = - \int_{\Omega} \phi(\sigma \, \nabla V + \frac{\partial A}{\partial t})
\end{equation}
++++

Dirichlet's conditions dictate that stem:[\int_{\Gamma} \frac{1}{\mu} \phi \cdot (\nabla \times A)\cdot n = 0].

We finally get the weak formulation:

[stem]
++++
\begin{equation}
\int_{\Omega} \frac{1}{\mu} \, (\nabla \times \phi) \cdot (\nabla \times A) = - \int_{\Omega} \phi(\sigma \, \nabla V + \frac{\partial A}{\partial t})
\end{equation}
++++

By the same way, let's consider the equation <<nConservation, (2)>> : Multiplying by stem:[\psi \in H_1(\Omega)] and integrating over stem:[\Omega] we get : 

[stem]
++++
\begin{equation}
\int_{\Omega} \psi \nabla \cdot (\sigma ( -\nabla V -\frac{\partial A}{\partial t})) = 0
\end{equation}
++++

Using the relationship: 

[stem]
++++
\nabla \cdot (uv) = v\nabla u + u \nabla \cdot v
++++

we get : 

[stem]
++++
\begin{equation}
\int_{\Omega} \nabla \cdot ( \psi \sigma ( -\nabla V -\frac{\partial A}{\partial t})) - \int_{\Omega} \sigma ( -\nabla V -\frac{\partial A}{\partial t}) \nabla \psi = 0
\end{equation} 
++++

By using the formula of divergence we finally get: 

[stem]
++++
\begin{equation}
\int_{\Gamma} \psi \sigma ( -\nabla V -\frac{\partial A}{\partial t}) \cdot n - \int_{\Omega} \sigma ( -\nabla V -\frac{\partial A}{\partial t}) \nabla \psi = 0
\end{equation} 
++++