= Modeling the transient behaviour of high field magnets

== Introduction

High-field magnets are becoming very popular with the scientific community. 
Indeed, they are proving increasingly useful in many fields, such as superconductivity or BioChemistry. 
Their development and maintenance represent a significant cost. 
Consequently, their uses are limited, and all requests for fields are submitted to a selection committee. 
This is why it is fundamental to understand and model perfectly beforehand the physical phenomenon that one wishes to observe via these magnets. 
The starting and stopping of the magnets follows this rule. 
During these phases, electromagnetic, thermal and mechanical phenomena come into play. 
Different interactions impose limitations, such as the induced current, creating a skin effect. This is why a theoretical, as well as numerical, validation of the start and stop phases would allow the maximum optimisation of the use of high field magnets, thus optimising their cost. 
For this purpose, we will study a formulation of Maxwell's equations, in the quasi-static case, i.e. the formulation in magnetic and electric potential.   

== Background

The National Laboratory for Intense Magnetic Fields (LNCMI), is a research infrastructure of the CNRS, located on two sites. Grenoble, where continuous fields are processed, and Toulouse, where pulsed fields are processed. It welcomes scientists from all over the world to carry out intense field experiments. France is thus positioned, alongside Germany, China and the United States, as the owner of the most powerful continuous field magnets in the world, capable of providing fields of up to 37 Tesla. The annual use of magnets in Grenoble (more than 3000h) pushes to understand as much as possible the different physical phenomena involved, in order to optimize the use of magnets as much as possible. This is why understanding the starting of magnets, as well as their stopping, is essential. A correct modelling of the phenomena coming into play in this period is therefore necessary. The principle is therefore, based on the magnetic and electrical potential model of Maxwell's equations, to accurately model the starting and stopping of magnets, including the skin effects that are created during these moments.
