site:
  title: Project // Docs
  url: /
  start_page: mqs:ROOT:index.adoc
content:
  sources:
  - url: ..
    branches: master
    start_path: docs
  - url: https://github.com/feelpp/toolbox
    branches: master
    start_path: examples
  - url: https://github.com/feelpp/book.feelpp.org
    branches: master
    start_path: docs/toolboxes
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: supplemental-ui
output:
  clean: true
  dir: public
asciidoc:
  attributes:
    project_version: 0.108
    deploymentRoot: ""
    numbered: true
    allow-uri-read: true
    hide-uri-scheme: true
    feelpp: Feel++
    angiotk: AngioTK
    4fastsim: 4FastSim
    stem: latexmath
    hemotumpp: Hemotum++
    eye2brain: Eye2Brain
    swimmer: Swimmer
