name: CI

on: [push]

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: buildkite/trigger-pipeline-action@v1.2.0
      env:
        BUILDKITE_API_ACCESS_TOKEN: ${{ secrets.BUILDKITE_API_ACCESS_TOKEN }}
        PIPELINE: "feelpp/cemosis-docs"
        COMMIT: "HEAD"
        BRANCH: "master"
        MESSAGE: ":github: Triggered from a GitHub Action by MQS Project"
  build_code:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Build MQS
      run: |
        mkdir build && cd build
        CXX=clang++-9 cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./install ..
        make -j3
        make install
    - name: Check build
      run: |
        mkdir check && cd check
        mpirun --bind-to core --mca btl vader,self -np 4 ../bin/feelpp_mqs_form --config-file ../qs/src/cases/mqs-blockform/const.cf 
      working-directory: build/install
    - name: Package
      run: |
        make package
        mkdir artifact && cp mqs*.tar.gz artifact
        ls -l artifact
        tar tzvf mqs*.tar.gz
      working-directory: build
#    - name: Upload artifact
#      uses: actions/upload-artifact@v1.0.0
#      with:
#        # Artifact name
#        name: MQS-${{ runner.os }} 
#        # Directory containing files to upload
#        path: build/install/
